# -*- coding: utf-8 -*-
"""data_pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pteFHSTHYS4MElzuTrxBx0C1wOUaDqJf
"""

!pip install fastmcp -q

import io
import pathlib
import pandas as pd

# los 50MB ya están en memoria en la variable "contenido"
# solo parsea con nrows=47000
df = pd.read_csv(io.BytesIO(contenido), encoding="utf-8-sig", on_bad_lines="skip", nrows=47000)
print(f"Filas cargadas: {len(df)}")

PROCESSED_DIR = pathlib.Path("/content/hw5_ds/mef_subnational_efficiency_mcp/data/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

PIM_COL = "PIM_2025"
DEVENGADO_COL = "DEVENGADO_2025"
NIVEL_GOB_COL = "NIVEL_GOBIERNO_NOMBRE"
NIVEL_GOB_VALUES = ["GOBIERNOS REGIONALES", "GOBIERNOS LOCALES"]
COLS_KEEP = ["EJECUTORA_NOMBRE", "DEPARTAMENTO_EJECUTORA_NOMBRE", NIVEL_GOB_COL, PIM_COL, DEVENGADO_COL]

df[PIM_COL] = pd.to_numeric(df[PIM_COL], errors="coerce").fillna(0)
df[DEVENGADO_COL] = pd.to_numeric(df[DEVENGADO_COL], errors="coerce").fillna(0)

mask = (df[PIM_COL] > 10_000_000) & (df[NIVEL_GOB_COL].isin(NIVEL_GOB_VALUES))
df_filtered = df[mask].copy()
print(f"Filas filtradas: {len(df_filtered)}")

df_filtered["Avance"] = df_filtered.apply(lambda r: round((r[DEVENGADO_COL] / r[PIM_COL]) * 100, 2) if r[PIM_COL] > 0 else 0.0, axis=1)
df_filtered["Saldo_No_Devengado"] = df_filtered[PIM_COL] - df_filtered[DEVENGADO_COL]

cols_final = COLS_KEEP + ["Avance", "Saldo_No_Devengado"]
df_filtered = df_filtered[[c for c in cols_final if c in df_filtered.columns]]

out = PROCESSED_DIR / "presupuesto_2025.parquet"
df_filtered.to_parquet(out, index=False)
print(f"Parquet guardado: {out}  ({len(df_filtered)} filas)")

print(df_filtered[["EJECUTORA_NOMBRE", "DEPARTAMENTO_EJECUTORA_NOMBRE", "NIVEL_GOBIERNO_NOMBRE", "PIM_2025", "DEVENGADO_2025", "Avance"]])

from google.colab import files
files.download("/content/hw5_ds/mef_subnational_efficiency_mcp/data/processed/presupuesto_2025.parquet")
files.download("/content/hw5_ds/mef_subnational_efficiency_mcp/data/snapshots/schema_snapshot_2025.csv")
files.download("/content/hw5_ds/mef_subnational_efficiency_mcp/data/snapshots/schema_2025.json")