# -*- coding: utf-8 -*-
"""mcp_server

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lwtooi-wnueERP1AWmIxuW1sLX2LUnm_
"""

!pip install fastmcp -q
from __future__ import annotations

import io
import json
import requests
import pandas as pd
from fastmcp import FastMCP

CKAN_BASE = "https://datosabiertos.mef.gob.pe"

_SESSION = requests.Session()
_SESSION.headers.update({"User-Agent": "mef-efficiency-mcp/1.0"})

mcp = FastMCP("MEF Subnational Efficiency MCP")

def _ckan_get(action: str, params: dict) -> dict:
    url = f"{CKAN_BASE}/api/3/action/{action}"
    resp = _SESSION.get(url, params=params, timeout=30)
    resp.raise_for_status()
    data = resp.json()
    if not data.get("success"):
        raise RuntimeError(f"CKAN error for '{action}': {data.get('error')}")
    return data["result"]

@mcp.tool()
def buscar_datasets(query: str, rows: int = 10) -> list[dict]:
    """Queries the portal with keyword strings via CKAN package_search."""
    result = _ckan_get("package_search", {"q": query, "rows": rows})
    return [
        {
            "id": pkg["id"],
            "name": pkg["name"],
            "title": pkg.get("title", ""),
            "organization": (pkg.get("organization") or {}).get("title", ""),
            "num_resources": pkg.get("num_resources", 0),
            "metadata_modified": pkg.get("metadata_modified", ""),
        }
        for pkg in result.get("results", [])
    ]


@mcp.tool()
def obtener_detalle_dataset(dataset_id: str) -> dict:
    """Extracts direct download URLs for data resources via CKAN package_show."""
    pkg = _ckan_get("package_show", {"id": dataset_id})
    return {
        "id": pkg["id"],
        "name": pkg["name"],
        "title": pkg.get("title", ""),
        "notes": (pkg.get("notes") or "")[:500],
        "resources": [
            {
                "id": r["id"],
                "name": r.get("name", ""),
                "format": r.get("format", ""),
                "url": r.get("url", ""),
                "datastore_active": r.get("datastore_active", False),
            }
            for r in pkg.get("resources", [])
        ],
    }


@mcp.tool()
def inspeccionar_esquema_csv(url_csv: str, max_rows: int = 10):
    """Opens a partial stream of a CSV resource. Returns at most max_rows rows."""
    import io
    resp = _SESSION.get(url_csv, stream=True, timeout=60)
    resp.raise_for_status()
    contenido = b""
    for chunk in resp.iter_content(chunk_size=1024):
        contenido += chunk
        if len(contenido) > 500_000:
            break
    resp.close()
    df = pd.read_csv(io.BytesIO(contenido), encoding="utf-8-sig", on_bad_lines="skip", nrows=max_rows)
    return df


@mcp.tool()
def consultar_datastore_filtrado(resource_id: str, sql_or_filters: str) -> list[dict]:
    """Performs SQL-like queries on the CKAN datastore.

    Pass a SQL string (SELECT ...) or a JSON string of filter params.
    """
    query = sql_or_filters.strip()
    if query.upper().startswith("SELECT"):
        result = _ckan_get("datastore_search_sql", {"sql": query})
        return result.get("records", [])

    try:
        filters = json.loads(query) if query else {}
    except json.JSONDecodeError:
        filters = {}
    params = {"resource_id": resource_id, "limit": 100}
    params.update(filters)
    result = _ckan_get("datastore_search", params)
    return result.get("records", [])


@mcp.tool()
def obtener_ultimas_actualizaciones(limit: int = 10) -> list[dict]:
    """Returns recently changed packages on the portal."""
    result = _ckan_get("recently_changed_packages_activity_list", {"limit": limit})
    activities = result if isinstance(result, list) else []
    return [
        {
            "id": act.get("id", ""),
            "timestamp": act.get("timestamp", ""),
            "activity_type": act.get("activity_type", ""),
            "package_id": act.get("object_id", ""),
        }
        for act in activities[:limit]
    ]


@mcp.tool()
def listar_entidades_publicas() -> list[dict]:
    """Fetches active public organizations from the portal."""
    result = _ckan_get("organization_list", {"all_fields": True, "limit": 50})
    orgs = result if isinstance(result, list) else []
    return [
        {
            "id": org.get("id", ""),
            "name": org.get("name", ""),
            "title": org.get("title", ""),
            "package_count": org.get("package_count", 0),
        }
        for org in orgs
    ]


if __name__ == "__main__":
    # mcp.run()
    print("MCP server definido correctamente")