# -*- coding: utf-8 -*-
"""data_pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pteFHSTHYS4MElzuTrxBx0C1wOUaDqJf
"""

"""2025 data snapshot and processing pipeline.

Persona 1 owns the implementation. This script must write small outputs only.
"""

from __future__ import annotations

import io
import json
from pathlib import Path

import requests
import pandas as pd

PROJECT_ROOT = pathlib.Path("/content/hw5_ds/mef_subnational_efficiency_mcp")
SNAPSHOT_DIR = PROJECT_ROOT / "data" / "snapshots"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

CSV_URL = "https://fs.datosabiertos.mef.gob.pe/datastorefiles/comparativo_gastos_2022_2026.csv"
PIM_COL = "PIM_2025"
DEVENGADO_COL = "DEVENGADO_2025"
PIM_THRESHOLD = 10_000_000
NIVEL_GOB_COL = "NIVEL_GOBIERNO_NOMBRE"
NIVEL_GOB_VALUES = ["Gobiernos Regionales", "Gobiernos Locales"]

COLS_KEEP = [
    "EJECUTORA_NOMBRE",
    "DEPARTAMENTO_EJECUTORA_NOMBRE",
    NIVEL_GOB_COL,
    PIM_COL,
    DEVENGADO_COL,
]

_SESSION = requests.Session()
_SESSION.headers.update({"User-Agent": "mef-efficiency-pipeline/1.0"})

import pathlib

PROJECT_ROOT = pathlib.Path("/content/hw5_ds/mef_subnational_efficiency_mcp")
SNAPSHOT_DIR = PROJECT_ROOT / "data" / "snapshots"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

create_schema_snapshot()
build_processed_budget()

import pathlib
PROJECT_ROOT = pathlib.Path("/content/hw5_ds/mef_subnational_efficiency_mcp")
(PROJECT_ROOT / "data" / "snapshots").mkdir(parents=True, exist_ok=True)
(PROJECT_ROOT / "data" / "processed").mkdir(parents=True, exist_ok=True)
print("carpetas creadas!")

create_schema_snapshot()
build_processed_budget()



def create_schema_snapshot() -> Path:
    """Download first 500KB of CSV, read 10 rows, save schema to data/snapshots/."""
    SNAPSHOT_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Fetching schema snapshot from {CSV_URL} ...")
    resp = _SESSION.get(CSV_URL, stream=True, timeout=60)
    resp.raise_for_status()

    contenido = b""
    for chunk in resp.iter_content(chunk_size=1024):
        contenido += chunk
        if len(contenido) > 500_000:
            break
    resp.close()

    df = pd.read_csv(
        io.BytesIO(contenido),
        encoding="utf-8-sig",
        on_bad_lines="skip",
        nrows=10,
    )

    out_csv = SNAPSHOT_DIR / "schema_snapshot_2025.csv"
    out_json = SNAPSHOT_DIR / "schema_2025.json"

    df.to_csv(out_csv, index=False)

    schema = {
        "columns": list(df.columns),
        "dtypes": {c: str(t) for c, t in df.dtypes.items()},
        "sample_rows": df.head(3).to_dict(orient="records"),
    }
    out_json.write_text(json.dumps(schema, ensure_ascii=False, indent=2))

    print(f"Schema snapshot saved: {out_csv}  ({len(df)} rows x {len(df.columns)} cols)")
    print(f"Columns: {list(df.columns)}")
    return out_json


def build_processed_budget() -> Path:
    """Filter PIM_2025 > 10M and regional/local govs, compute metrics, write Parquet."""
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Processing budget data from {CSV_URL} ...")
    chunks = []

    for chunk in pd.read_csv(
        CSV_URL,
        chunksize=10_000,
        encoding="utf-8-sig",
        on_bad_lines="skip",
        low_memory=False,
    ):
        # convert PIM and DEVENGADO to numeric
        chunk[PIM_COL] = pd.to_numeric(chunk[PIM_COL], errors="coerce").fillna(0)
        chunk[DEVENGADO_COL] = pd.to_numeric(chunk[DEVENGADO_COL], errors="coerce").fillna(0)

        # filter PIM > 10M and regional/local governments
        mask = (
            (chunk[PIM_COL] > PIM_THRESHOLD) &
            (chunk[NIVEL_GOB_COL].isin(NIVEL_GOB_VALUES))
        )
        filtered = chunk[mask].copy()

        if filtered.empty:
            continue

        # calculate metrics
        filtered["Avance"] = filtered.apply(
            lambda r: round((r[DEVENGADO_COL] / r[PIM_COL]) * 100, 2) if r[PIM_COL] > 0 else 0.0,
            axis=1,
        )
        filtered["Saldo_No_Devengado"] = filtered[PIM_COL] - filtered[DEVENGADO_COL]

        # keep only needed columns
        cols_final = COLS_KEEP + ["Avance", "Saldo_No_Devengado"]
        filtered = filtered[[c for c in cols_final if c in filtered.columns]]

        chunks.append(filtered)
        print(f"  Chunk processed: {len(filtered)} rows kept after filter")

    if not chunks:
        raise RuntimeError("No rows matched the filter criteria. Check the data.")

    df_final = pd.concat(chunks, ignore_index=True)

    out = PROCESSED_DIR / "presupuesto_2025.parquet"
    df_final.to_parquet(out, index=False)
    print(f"Processed budget saved: {out}  ({len(df_final)} rows)")
    return out


if __name__ == "__main__":
    create_schema_snapshot()
    build_processed_budget()

from __future__ import annotations
import io
import json
import pathlib
import requests
import pandas as pd

PROJECT_ROOT = pathlib.Path("/content/hw5_ds/mef_subnational_efficiency_mcp")
SNAPSHOT_DIR = PROJECT_ROOT / "data" / "snapshots"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

CSV_URL = "https://fs.datosabiertos.mef.gob.pe/datastorefiles/comparativo_gastos_2022_2026.csv"
PIM_COL = "PIM_2025"
DEVENGADO_COL = "DEVENGADO_2025"
PIM_THRESHOLD = 10_000_000
NIVEL_GOB_COL = "NIVEL_GOBIERNO_NOMBRE"
NIVEL_GOB_VALUES = ["Gobiernos Regionales", "Gobiernos Locales"]
COLS_KEEP = ["EJECUTORA_NOMBRE", "DEPARTAMENTO_EJECUTORA_NOMBRE", NIVEL_GOB_COL, PIM_COL, DEVENGADO_COL]

_SESSION = requests.Session()
_SESSION.headers.update({"User-Agent": "mef-efficiency-pipeline/1.0"})

def create_schema_snapshot():
    SNAPSHOT_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Fetching schema snapshot from {CSV_URL} ...")
    resp = _SESSION.get(CSV_URL, stream=True, timeout=60)
    resp.raise_for_status()
    contenido = b""
    for chunk in resp.iter_content(chunk_size=1024):
        contenido += chunk
        if len(contenido) > 500_000:
            break
    resp.close()
    df = pd.read_csv(io.BytesIO(contenido), encoding="utf-8-sig", on_bad_lines="skip", nrows=10)
    out_csv = SNAPSHOT_DIR / "schema_snapshot_2025.csv"
    out_json = SNAPSHOT_DIR / "schema_2025.json"
    df.to_csv(out_csv, index=False)
    schema = {"columns": list(df.columns), "dtypes": {c: str(t) for c, t in df.dtypes.items()}, "sample_rows": df.head(3).to_dict(orient="records")}
    out_json.write_text(json.dumps(schema, ensure_ascii=False, indent=2))
    print(f"Schema snapshot saved: {out_csv}  ({len(df)} rows x {len(df.columns)} cols)")
    return out_json

def build_processed_budget():
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Processing budget data from {CSV_URL} ...")
    chunks = []
    for chunk in pd.read_csv(CSV_URL, chunksize=10_000, encoding="utf-8-sig", on_bad_lines="skip", low_memory=False):
        chunk[PIM_COL] = pd.to_numeric(chunk[PIM_COL], errors="coerce").fillna(0)
        chunk[DEVENGADO_COL] = pd.to_numeric(chunk[DEVENGADO_COL], errors="coerce").fillna(0)
        mask = (chunk[PIM_COL] > PIM_THRESHOLD) & (chunk[NIVEL_GOB_COL].isin(NIVEL_GOB_VALUES))
        filtered = chunk[mask].copy()
        if filtered.empty:
            continue
        filtered["Avance"] = filtered.apply(lambda r: round((r[DEVENGADO_COL] / r[PIM_COL]) * 100, 2) if r[PIM_COL] > 0 else 0.0, axis=1)
        filtered["Saldo_No_Devengado"] = filtered[PIM_COL] - filtered[DEVENGADO_COL]
        cols_final = COLS_KEEP + ["Avance", "Saldo_No_Devengado"]
        filtered = filtered[[c for c in cols_final if c in filtered.columns]]
        chunks.append(filtered)
        print(f"  Chunk processed: {len(filtered)} rows kept after filter")
    if not chunks:
        raise RuntimeError("No rows matched the filter criteria.")
    df_final = pd.concat(chunks, ignore_index=True)
    out = PROCESSED_DIR / "presupuesto_2025.parquet"
    df_final.to_parquet(out, index=False)
    print(f"Processed budget saved: {out}  ({len(df_final)} rows)")
    return out

# correr
create_schema_snapshot()
build_processed_budget()

import json
import pandas as pd
import pathlib

SNAPSHOT_DIR = pathlib.Path("/content/hw5_ds/mef_subnational_efficiency_mcp/data/snapshots")
SNAPSHOT_DIR.mkdir(parents=True, exist_ok=True)

# columnas reales que ya confirmamos antes
columnas = [
    "KEY_VALUE", "NIVEL_GOBIERNO", "NIVEL_GOBIERNO_NOMBRE", "SECTOR", "SECTOR_NOMBRE",
    "PLIEGO", "PLIEGO_NOMBRE", "EJECUTORA", "EJECUTORA_NOMBRE", "SEC_EJEC",
    "DEPARTAMENTO_EJECUTORA", "DEPARTAMENTO_EJECUTORA_NOMBRE", "PROVINCIA_EJECUTORA",
    "PROVINCIA_EJECUTORA_NOMBRE", "DISTRITO_EJECUTORA", "DISTRITO_EJECUTORA_NOMBRE",
    "PROGRAMA_PPTO", "PROGRAMA_PPTO_NOMBRE", "PIM_2025", "DEVENGADO_2025", "GIRADO_2025"
]

schema = {
    "source": "https://fs.datosabiertos.mef.gob.pe/datastorefiles/comparativo_gastos_2022_2026.csv",
    "columns": columnas,
    "key_columns": {
        "PIM": "PIM_2025",
        "DEVENGADO": "DEVENGADO_2025",
        "NIVEL_GOBIERNO": "NIVEL_GOBIERNO_NOMBRE",
        "REGION": "DEPARTAMENTO_EJECUTORA_NOMBRE",
        "ENTIDAD": "EJECUTORA_NOMBRE"
    },
    "note": "Schema inspeccionado via stream 500KB. Columnas verificadas manualmente."
}

out_json = SNAPSHOT_DIR / "schema_2025.json"
out_json.write_text(json.dumps(schema, ensure_ascii=False, indent=2))
print("schema_2025.json guardado!")